name: PlatformIO CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache PlatformIO dependencies
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -U platformio

      - name: Build PlatformIO project
        run: pio run -e esp32dev

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: display-thing-fw
          path: .pio/build/esp32dev/firmware.bin
